### ISSUE TITLE
Unresolved reference.

### ISSUE THREAD

**Issue by sexy-angel-demon-gojo** [rusinikita/movies-shmoovies#1]
Добрый день.
Периодически возникает проблема (скриншот прекрепил) в случайном месте.
Возникает после того, как я что-то верстаю (лайаут для активити) и в совершенно другом месте, которое я никак не использовал и не трогал выскакивают такие ошибки с теми айтемами, что я наверстал.
<img width="1280" alt="2017-03-30 16 02 41" src="https://cloud.githubusercontent.com/assets/22638529/24508069/aaaff252-1562-11e7-9f32-02fd51b6a03b.png">

**Comment by DAPolyakov** [comment]
У меня была такая проблема. Возникает, если изменить id объекту и применить
его ко всему проекту (обычное изменение айдишника мышкой).
Так, если был объект с id TextView и мы его изменили, то студия помимо всех
обращений по этому айди поломает тип TextView объявленных переменных.

30.03.2017 16:06 пользователь "Pavel" <notifications@github.com> написал:

**Comment by rusinikita** [comment]
Да, ты видимо присвоил вьюхе `id="@id/textView"` а затем `SHIFT + F6` переименовал  в `ma_about`. Если такое случается помогает просто `CTRL + Z`. Когда пользуешься рефакторинком подиагонали просматривай что идея собирается изменить.
